- worlds/rain_world/__init__.py
- worlds/rain_world/locations/tokens_pearls.py
Filtered out "BroadcastMisc" pearls when reading in game data
Ran tests and generated a seed to validate pearls are no longer present
> HOTFIX: Fix generic pearls in generation

- worlds/rain_world/__init__.py
- Desired gate behavior is now sent through slot data
- Reverted random starting region to send raw option through slot data again
> Slot data modifications

- worlds/rain_world/conditions/__init__.py
- worlds/rain_world/conditions/gamestate.py
- worlds/rain_world/events/world.py
- worlds/rain_world/locations/tokens_pearls.py
- worlds/rain_world/options.py
- worlds/rain_world/test/test_generic.py
- worlds/rain_world/utils.py
The inconsistencies with all the different filtering methods for checks should be handled more explicitly.  Closes #86.
> Fix whitelist/blacklist/filter/conditional accessibility issues

- worlds/rain_world/events/world.py
While the check did require the mark, the static event (used for The Scholar) did not.  Closes #90.
> Require mark for meeting LttM

- worlds/rain_world/regions/physical.py
UW is now split up into a few regions to close #96.  Turns out even having rarefaction cell doesn't really work there so, for now, westward through Underhang as Rivulet is entirely out of logic.
> Change UW accesssibility

- worlds/rain_world/locations/classes.py
- worlds/rain_world/locations/echoes.py
- worlds/rain_world/locations/foodquest.py
- worlds/rain_world/locations/passages.py
- worlds/rain_world/locations/tokens_pearls.py
- worlds/rain_world/locations/unique.py
Closes #53; even though it doesn't address everything listed there, most of it is unnecessary so it is being closed for now.
Also fixes several niche bugs found along the way:
- SL echo is now placed in the correct subregion
- broadcast generation now properly considers accessibility (relevant for when broadcasts become available to other slugcats)
- Meet_FP now requires mark for sofanthiel
> LocationData refactor

- worlds/rain_world/__init__.py
- worlds/rain_world/locations/__init__.py
- worlds/rain_world/locations/shelters.py
- worlds/rain_world/options.py
Implements sheltersanity.  Closes #102.  Contingent on SaltiestSyrup/RWRandomizer#44.
> Add sheltersanity

- worlds/rain_world/options.py
- worlds/rain_world/regions/classes.py
> Add option to exclude MS by default

- worlds/rain_world/regions/physical.py
Expand both the filtration and sump tunnel subregions.
> Tweak Pipeyard subregions

- worlds/rain_world/locations/tokens_pearls.py
Fixes #117.  [See map](https://rain-world-downpour-map.github.io/map.html?slugcat=red&region=GW&room=GW_A14).
> Make RedLizard token require Bubble Grass

- worlds/rain_world/locations/foodquest.py
- worlds/rain_world/options.py
This setting should be strictly opt-in.
> Make extreme threats a boolean setting

- worlds/rain_world/regions/classes.py
- worlds/rain_world/regions/physical.py
> Fix SU and OE subregions

- worlds/rain_world/events/world.py
- worlds/rain_world/game_data/general.py
> Fix accessibility failure when Watcher is enabled

- worlds/rain_world/regions/gates.py
> Fix gates to Filtration not requiring glow

- worlds/rain_world/items.py
> Make longer cycles a progression item

- worlds/rain_world/__init__.py
- worlds/rain_world/options.py
> Prevent ZeroDivisionError when setting all weights to zero

- worlds/rain_world/regions/warping.py
- worlds/rain_world/utils.py
> Use more robust necklace method for generating a derangement

- worlds/rain_world/__init__.py
- worlds/rain_world/items.py
- worlds/rain_world/regions/gates.py
- worlds/rain_world/regions/physical.py
> Eliminate Option-Glow

- worlds/rain_world/items.py
- worlds/rain_world/options.py
Enabled the new traps added in https://github.com/SaltiestSyrup/RWRandomizer/pull/85
Simplified the trap weights to be more spread out and favor the common traps slightly less
> Enable new traps

- worlds/rain_world/locations/tokens_pearls.py
> Remove pearl checks for vanilla Monk

- worlds/rain_world/game_data/watcher.py
- worlds/rain_world/regions/warping.py
> Give all regions a predetermined warp target

- worlds/rain_world/docs/watcher_en.md
- worlds/rain_world/locations/__init__.py
- worlds/rain_world/locations/watcher.py
- worlds/rain_world/options.py
> Implement thronewarp and prince checks

- worlds/rain_world/regions/classes.py
> Fix rotted generation logic not working

- worlds/rain_world/game_data/bitflag.py
- worlds/rain_world/game_data/general.py
- worlds/rain_world/locations/__init__.py
- worlds/rain_world/locations/classes.py
- worlds/rain_world/locations/flowers.py
- worlds/rain_world/locations/shelters.py
- worlds/rain_world/options.py
> Rewrite of shelter and flower checks

- worlds/rain_world/docs/naming_en.md
- worlds/rain_world/locations/classes.py
- worlds/rain_world/locations/echoes.py
- worlds/rain_world/locations/flowers.py
- worlds/rain_world/locations/shelters.py
- worlds/rain_world/locations/tokens_pearls.py
- worlds/rain_world/locations/watcher.py
Adds location groups for some player YAML settings and `!hint_location`.  Public documentation updated to match.
> Implement location groups

- worlds/rain_world/game_data/shelters.py
> Raise `OptionError` on bad YAML instead of `ValueError`

- worlds/rain_world/game_data/general.py
- worlds/rain_world/locations/passages.py
Closes #213.  Fixes the generation failure that occurs for this player YAML with seed `483331571`:
```
description: Rain World Template, generated with https://github.com/Eijebong/Archipelago-fuzzer
game: Rain World
requires:
version: 0.6.1
Rain World:
which_game_version: '1_9_15_3'
is_msc_enabled: 'false'
is_watcher_enabled: 'false'
which_campaign: yellow
passage_progress_without_survivor: enabled
which_victory_condition: ascension
which_gate_behavior: key_and_karma
death_link: 'false'
random_starting_region: undergrowth
progression_balancing: 59
accessibility: items
difficulty_monk: 1
difficulty_hunter: 1
difficulty_outlaw: 8
difficulty_nomad: 7
difficulty_chieftain: 'false'
difficulty_glow: 'true'
difficulty_extreme_threats: 'false'
difficulty_submerged: 'false' …
```
> Let The Outlaw consider some non-lizard creatures

- worlds/rain_world/events/classes.py
- worlds/rain_world/locations/classes.py
- worlds/rain_world/regions/classes.py
- worlds/rain_world/regions/gates.py
- worlds/rain_world/utils_ap.py
> Don't generate regions that won't be used

- worlds/rain_world/regions/classes.py
Related to #210 and #217 - a few regions went uncaught since their inaccessibility was a little more nuanced.
> Prevent a few more regions from generating when inaccessible

- worlds/rain_world/game_data/shelters.py
- worlds/rain_world/options.py
Adds some more detection for generation failures due to a small sphere 1.
> Expand detection of general generation failure conditions
